version: "3.0"
services:
    nginx:
        build: ./docker-images/nginx
        ports:
            - "9394:80"
        depends_on:
            - php
    php:
        build: ./docker-images/php
        volumes:
            - ./src/:/var/www
        working_dir: /var/www/public
        depends_on:
            - mysql
            - redis
        ports:
            - "9000:9000"
        environment:
            - "DB_HOST=mysql"
            - "DB_PORT=${DB_PORT}"
            - "REDIS_HOST=redis"
            - "REDIS_PORT=${CACHE_PORT}"
    mysql:
        image: mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
            - "MYSQL_USER=${DB_USERNAME}"
            - "MYSQL_PASSWORD=${DB_PASSWORD}"
            - "MYSQL_DATABASE=${DB_DATABASE}"
        ports:
            - "3306:${DB_PORT}"
    redis:
        image: redis
        ports:
            - "6379:${CACHE_PORT}"